[
  {
    _id: "62cd5bcb2fd20152dfdd3396",
    index: 0,
    guid: "843dd655-09d3-4c6d-b7d8-454cc7565619",
    isActive: true,
    balance: "$3,391.31",
    picture: "http://placehold.it/32x32",
    age: 33,
    eyeColor: "green",
    name: "Kaufman Sweet",
    gender: "male",
    company: "ZORROMOP",
    email: "kaufmansweet@zorromop.com",
    phone: "+1 (997) 586-2715",
    address: "650 Cox Place, Dundee, North Dakota, 8345",
    about:
      "Reprehenderit aliqua aute nisi non voluptate sit consectetur. Occaecat Lorem consectetur cupidatat deserunt commodo enim sint adipisicing deserunt. Culpa proident ea aute id. Quis labore magna dolore laboris reprehenderit. Dolore ullamco nulla occaecat officia quis mollit fugiat. Lorem velit aliquip nisi sit culpa enim duis culpa incididunt non dolor elit est ad. Dolore nisi voluptate elit aute elit labore voluptate pariatur et laborum.\r\n",
    registered: "2021-12-22T01:20:56 -06:-30",
    latitude: 53.249332,
    longitude: 108.38832,
    tags: ["magna", "anim", "dolor", "enim", "nulla", "elit", "laborum"],
    friends: [
      {
        id: 0,
        name: "Josefina Gomez",
      },
      {
        id: 1,
        name: "Gale Newton",
      },
      {
        id: 2,
        name: "Althea Fuller",
      },
    ],
    greeting: "Hello, Kaufman Sweet! You have 3 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62cd5bcb4f1e1554d2842503",
    index: 1,
    guid: "f25168ff-5691-4a68-8b35-cc23870c7c1a",
    isActive: true,
    balance: "$2,024.44",
    picture: "http://placehold.it/32x32",
    age: 24,
    eyeColor: "blue",
    name: "Lynne Levine",
    gender: "female",
    company: "MAZUDA",
    email: "lynnelevine@mazuda.com",
    phone: "+1 (863) 457-3770",
    address: "475 Borinquen Pl, Sedley, Illinois, 1209",
    about:
      "Lorem officia do occaecat incididunt dolor minim quis id esse adipisicing irure officia do aute. Lorem aliquip elit tempor irure pariatur cillum nulla labore Lorem consequat dolor cillum eiusmod aliqua. Ad occaecat eiusmod nostrud dolor officia non laborum quis culpa.\r\n",
    registered: "2021-09-11T11:08:02 -06:-30",
    latitude: -10.867482,
    longitude: 24.038344,
    tags: [
      "dolore",
      "dolor",
      "exercitation",
      "proident",
      "adipisicing",
      "ipsum",
      "duis",
    ],
    friends: [
      {
        id: 0,
        name: "Jimmie Dale",
      },
      {
        id: 1,
        name: "Rae Puckett",
      },
      {
        id: 2,
        name: "Ida Bean",
      },
    ],
    greeting: "Hello, Lynne Levine! You have 5 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62cd5bcbae37b65fdb5f8f42",
    index: 2,
    guid: "02268d66-0fb7-498c-94a7-2ab6c30c9190",
    isActive: true,
    balance: "$3,379.46",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "blue",
    name: "Greene Grimes",
    gender: "male",
    company: "PORTICA",
    email: "greenegrimes@portica.com",
    phone: "+1 (848) 417-2898",
    address: "312 Grattan Street, Oasis, Nebraska, 232",
    about:
      "Veniam veniam ex reprehenderit elit nisi sint nulla minim. Sunt voluptate culpa mollit ad occaecat laborum. Anim enim adipisicing consectetur reprehenderit officia fugiat. Do aliqua pariatur dolor duis laboris exercitation sint eiusmod reprehenderit do laboris tempor nulla ipsum. Elit non est commodo anim nisi esse elit dolor excepteur excepteur laborum et culpa irure.\r\n",
    registered: "2019-04-30T11:51:18 -06:-30",
    latitude: -69.164,
    longitude: -108.644328,
    tags: ["tempor", "ut", "quis", "ad", "incididunt", "nulla", "eiusmod"],
    friends: [
      {
        id: 0,
        name: "Herrera Burke",
      },
      {
        id: 1,
        name: "Molly Valentine",
      },
      {
        id: 2,
        name: "Mullen Barker",
      },
    ],
    greeting: "Hello, Greene Grimes! You have 10 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62cd5bcbfc84639574785484",
    index: 3,
    guid: "2ce77e13-36f4-45cc-90d6-8cb065d9d27e",
    isActive: true,
    balance: "$1,216.29",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "green",
    name: "Martha Richards",
    gender: "female",
    company: "QUANTALIA",
    email: "martharichards@quantalia.com",
    phone: "+1 (925) 565-3098",
    address: "477 Wilson Avenue, Alfarata, Guam, 4892",
    about:
      "Proident laboris eu enim est anim do fugiat ad officia. Laborum aliquip esse cupidatat minim minim. Officia consequat ipsum adipisicing elit.\r\n",
    registered: "2022-01-21T06:34:11 -06:-30",
    latitude: -35.095806,
    longitude: 26.805274,
    tags: [
      "tempor",
      "officia",
      "deserunt",
      "incididunt",
      "officia",
      "officia",
      "aliqua",
    ],
    friends: [
      {
        id: 0,
        name: "April Shepard",
      },
      {
        id: 1,
        name: "Viola Rosario",
      },
      {
        id: 2,
        name: "Kathrine Morin",
      },
    ],
    greeting: "Hello, Martha Richards! You have 3 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "62cd5bcbdcc1850b62c81c21",
    index: 4,
    guid: "58f8785c-c223-4e79-aab2-48c65f422b3b",
    isActive: true,
    balance: "$1,323.25",
    picture: "http://placehold.it/32x32",
    age: 34,
    eyeColor: "green",
    name: "Josefa Dawson",
    gender: "female",
    company: "SULTRAXIN",
    email: "josefadawson@sultraxin.com",
    phone: "+1 (937) 564-3881",
    address: "689 Bridge Street, Brandywine, New Jersey, 6390",
    about:
      "Voluptate ut occaecat id elit pariatur elit eu excepteur cillum commodo do. Pariatur et quis proident consectetur excepteur. Pariatur anim magna magna Lorem in sunt consequat.\r\n",
    registered: "2021-03-11T02:58:19 -06:-30",
    latitude: -51.052292,
    longitude: -144.757235,
    tags: ["do", "do", "nisi", "labore", "elit", "irure", "reprehenderit"],
    friends: [
      {
        id: 0,
        name: "Thornton Alston",
      },
      {
        id: 1,
        name: "Walters Garrison",
      },
      {
        id: 2,
        name: "Pittman Carlson",
      },
    ],
    greeting: "Hello, Josefa Dawson! You have 8 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "62cd5bcbdc0bd1183f3824f3",
    index: 5,
    guid: "0b823cfe-e1e8-4451-be4a-1294d9e412f3",
    isActive: true,
    balance: "$1,957.84",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "blue",
    name: "Morrow Elliott",
    gender: "male",
    company: "ZIZZLE",
    email: "morrowelliott@zizzle.com",
    phone: "+1 (949) 527-2064",
    address: "387 Post Court, Wheatfields, Alabama, 3292",
    about:
      "Est elit eiusmod et pariatur pariatur sit aute dolore amet elit laboris commodo sit velit. Eiusmod labore anim fugiat deserunt ullamco ad nostrud in cupidatat cillum fugiat. Esse qui consectetur occaecat dolor proident duis enim velit cupidatat. Irure veniam proident voluptate sunt officia nostrud dolor aute magna ad sint qui officia. Amet ullamco elit magna velit amet aliqua quis id magna sint aute irure. Pariatur nulla consectetur dolore non velit tempor commodo.\r\n",
    registered: "2015-09-28T02:27:18 -06:-30",
    latitude: 13.703159,
    longitude: -116.365663,
    tags: ["quis", "dolore", "veniam", "cillum", "duis", "sint", "ipsum"],
    friends: [
      {
        id: 0,
        name: "Kayla Warren",
      },
      {
        id: 1,
        name: "Rena Hewitt",
      },
      {
        id: 2,
        name: "Phyllis Leonard",
      },
    ],
    greeting: "Hello, Morrow Elliott! You have 4 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "62cd5bccff67eaa6a92ced88",
    index: 6,
    guid: "62bb91a8-499e-40e4-9b96-cedbd2037230",
    isActive: false,
    balance: "$2,878.56",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "blue",
    name: "Tami Payne",
    gender: "female",
    company: "PROVIDCO",
    email: "tamipayne@providco.com",
    phone: "+1 (817) 533-3223",
    address: "422 Bragg Street, Saranap, Indiana, 9839",
    about:
      "Consectetur pariatur ullamco eu eu labore ad irure in. Lorem in velit esse esse velit ut sit laboris minim. Quis sint nisi eu dolor officia. Dolor pariatur amet do non aliquip. Nostrud est voluptate nisi esse.\r\n",
    registered: "2016-01-29T12:45:06 -06:-30",
    latitude: -8.052248,
    longitude: -156.498943,
    tags: ["in", "ea", "eiusmod", "nisi", "cupidatat", "et", "consectetur"],
    friends: [
      {
        id: 0,
        name: "Tabitha Chavez",
      },
      {
        id: 1,
        name: "Leola Hansen",
      },
      {
        id: 2,
        name: "Flora Jenkins",
      },
    ],
    greeting: "Hello, Tami Payne! You have 3 unread messages.",
    favoriteFruit: "apple",
  },
];
