version: "3.4"

services:
  flipkart_mysql:
    image: flipkart_mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - redis
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aditya@123

  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: unless-stopped
    ports:
      - 3500:6379
