version: "3.4"

services:
  flipkart_mysql:
    image: flipkart_mysql1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_INITDB_ROOT_USERNAME: Aditya
      MYSQL_INITDB_ROOT_PASSWORD: Aditya@123

  nginx:
    image: nginx:alpine
    container_name: webserver1
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: redis1
    restart: unless-stopped
    ports:
      - 3502:6379
